### ISSUE TITLE
tracer not found

### ISSUE THREAD

**Issue by 0xmountaintop** [scroll-tech/go-ethereum#148]
```
testnet-l2geth_service-1         | 2022-08-22T20:07:45.720744394Z WARN [08-22|20:07:45.720] Failed to compile tracer                 err="SyntaxError: unterminated statement (line 445)"
testnet-l2geth_service-1         | 2022-08-22T20:07:45.720746424Z WARN [08-22|20:07:45.720] Served debug_traceTransaction            conn=172.18.0.5:50510 reqid=0   t=21.916617ms err="tracer not found"
```

**Comment by mask-pp** [comment]
the issue link: https://github.com/blockscout/blockscout/issues/5935

[#5935 server log a lot of error msgs "tracer not found"](https://github.com/blockscout/blockscout/issues/5935)

The reason is that there `debug_traceTransaction` 's second param `{tracer: }` content is not right. 

We just need to use https://github.com/blockscout/blockscout/releases/tag/v4.1.7-beta.

**Comment by 0xmountaintop** [comment]
cloised via https://github.com/scroll-tech/testnet/pull/115
