### ISSUE TITLE
TODO: keep track of state_after account_proof

### ISSUE THREAD

**Issue by 0xmountaintop** [scroll-tech/go-ethereum#57]
We lose the tracking of state_after account_proof.

Simple way:
...

Complicated way:
...

How to refactor and simplify the codes....

**Comment by noel2004** [comment]
Updating the proof for account (and also the storage) among execution of a tx seems to be costly and the storage circuit must not  obtain these information for their witness because they can deduce the merkle path by theirself from the beginning state and the delta data (the updated account data and storage key/value pairs).

I purpose a improvment like following:

+ Add a field of AccountProof: map[string][]string in StructLogRes structure for recording all the proofs BEFORE tx begins of accounts which would be updated inside the tx
+ Remove Proof field in AccountProofWrapper, so we only need several AccountProofWrapper objects inside the ProofList field for the account state BEFORE and AFTER an execution of specified opcode.

We can also apply the similar way for handling the storage part: i.e., recording all the proofs for affected key of each accounts inside the tx and only record the key/value updating in StructLogRes structure for the specified opcode
